@startuml jwt

hide empty description

state Empty {
    [*] -> EFresh
    EFresh -> EStale : Time
    EStale -> EFresh : Challenge
}

state Authed {
    [*] -> AStale
    AFresh -> AStale : Time
    AStale -> AFresh : Challenge
}

[*] -> NoToken
NoToken -> Empty : Challenge
NoToken -> Authed : Login

@enduml
