on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-frontend.yaml'
      - 'frontend/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Setup pnpm
        run: |-
          corepack enable
          pnpm --version

      - name: Install packages
        working-directory: frontend
        run: pnpm install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4

      - name: Build
        working-directory: frontend
        run: pnpm vite build
        env:
          BASE_URL: ${{ steps.pages.outputs.base_path }}

      - name: Type check
        working-directory: frontend
        run: pnpm tsc

      - name: Lint
        working-directory: frontend
        run: pnpm xo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2
        with:
          path: frontend/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@13b55b33dd8996121833dbc1db458c793a334630 # v3
